services:
  n8n:
    image: n8nio/n8n:latest
    container_name: evolvian_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_ENCRYPTION_KEY=super_secret_123456789
      - GENERIC_TIMEZONE=America/Mexico_City
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data:
