import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from api.modules.assistant_rag.intent_detector import (
    INTENT_CANCEL_APPOINTMENT,
    INTENT_CHECK_AVAILABILITY,
    INTENT_CONFIRM_APPOINTMENT,
    INTENT_CREATE_APPOINTMENT,
    INTENT_RESCHEDULE_APPOINTMENT,
    detect_appointment_intent,
)


CASES = [
    ("Quiero agendar una cita", INTENT_CREATE_APPOINTMENT),
    ("Necesito una cita", INTENT_CREATE_APPOINTMENT),
    ("Me gustaría reservar una cita", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo agendar una cita?", INTENT_CREATE_APPOINTMENT),
    ("Quiero reservar un espacio", INTENT_CREATE_APPOINTMENT),
    ("Necesito apartar una cita", INTENT_CREATE_APPOINTMENT),
    ("Quiero programar una cita", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo sacar una cita?", INTENT_CREATE_APPOINTMENT),
    ("Quisiera una cita con ustedes", INTENT_CREATE_APPOINTMENT),
    ("Me gustaría agendar una consulta", INTENT_CREATE_APPOINTMENT),
    ("¿Tienen citas disponibles?", INTENT_CHECK_AVAILABILITY),
    ("Necesito una consulta", INTENT_CREATE_APPOINTMENT),
    ("Quiero ver disponibilidad", INTENT_CHECK_AVAILABILITY),
    ("¿Cuándo puedo agendar una cita?", INTENT_CHECK_AVAILABILITY),
    ("Quiero reservar una consulta", INTENT_CREATE_APPOINTMENT),
    ("Necesito una cita para mañana", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo reservar para hoy?", INTENT_CREATE_APPOINTMENT),
    ("¿Me pueden dar una cita?", INTENT_CREATE_APPOINTMENT),
    ("Quiero hacer una reservación", INTENT_CREATE_APPOINTMENT),
    ("Quiero agendar con ustedes", INTENT_CREATE_APPOINTMENT),
    ("¿Tienen citas mañana?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios tienen disponibles?", INTENT_CHECK_AVAILABILITY),
    ("¿Hay espacio hoy?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios hay mañana?", INTENT_CHECK_AVAILABILITY),
    ("¿Cuándo tienen espacio?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué días tienen citas?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios tienen esta semana?", INTENT_CHECK_AVAILABILITY),
    ("¿Hay citas hoy en la tarde?", INTENT_CHECK_AVAILABILITY),
    ("¿Hay disponibilidad hoy?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios hay por la mañana?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios tienen por la tarde?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horario es el más temprano?", INTENT_CHECK_AVAILABILITY),
    ("¿Cuál es el último horario disponible?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué días tienen libre?", INTENT_CHECK_AVAILABILITY),
    ("¿Puedo ver sus horarios?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios quedan?", INTENT_CHECK_AVAILABILITY),
    ("¿Hay huecos disponibles hoy?", INTENT_CHECK_AVAILABILITY),
    ("¿Tienen espacio en la agenda?", INTENT_CHECK_AVAILABILITY),
    ("¿Hay disponibilidad esta semana?", INTENT_CHECK_AVAILABILITY),
    ("¿Qué horarios me recomiendas?", INTENT_CHECK_AVAILABILITY),
    ("Quiero agendar para mañana", INTENT_CREATE_APPOINTMENT),
    ("¿Tienen algo para el viernes?", INTENT_CHECK_AVAILABILITY),
    ("Quiero una cita el lunes", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo agendar para el martes?", INTENT_CREATE_APPOINTMENT),
    ("Quiero una cita el sábado", INTENT_CREATE_APPOINTMENT),
    ("Necesito una cita el 15", INTENT_CREATE_APPOINTMENT),
    ("Quiero una cita el 20 de junio", INTENT_CREATE_APPOINTMENT),
    ("¿Hay algo el miércoles?", INTENT_CHECK_AVAILABILITY),
    ("Necesito una cita esta semana", INTENT_CREATE_APPOINTMENT),
    ("Quiero una cita la próxima semana", INTENT_CREATE_APPOINTMENT),
    ("Quiero una cita mañana a las 3", INTENT_CREATE_APPOINTMENT),
    ("Quiero agendar a las 10", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo ir hoy a las 4?", INTENT_CREATE_APPOINTMENT),
    ("¿Tienen algo a las 11?", INTENT_CHECK_AVAILABILITY),
    ("Necesito cita a las 2", INTENT_CREATE_APPOINTMENT),
    ("Quiero reservar a las 5", INTENT_CREATE_APPOINTMENT),
    ("¿Hay cita a las 9?", INTENT_CHECK_AVAILABILITY),
    ("Quiero a las 12", INTENT_CREATE_APPOINTMENT),
    ("¿Puedo a las 6?", INTENT_CHECK_AVAILABILITY),
    ("Quiero a las 3 de la tarde", INTENT_CREATE_APPOINTMENT),
    ("Quiero cambiar mi cita", INTENT_RESCHEDULE_APPOINTMENT),
    ("Necesito mover mi cita", INTENT_RESCHEDULE_APPOINTMENT),
    ("¿Puedo cambiar mi cita?", INTENT_RESCHEDULE_APPOINTMENT),
    ("Quiero cancelar mi cita", INTENT_CANCEL_APPOINTMENT),
    ("Necesito cancelar mi cita", INTENT_CANCEL_APPOINTMENT),
    ("¿Puedo reagendar?", INTENT_RESCHEDULE_APPOINTMENT),
    ("Quiero reprogramar", INTENT_RESCHEDULE_APPOINTMENT),
    ("No podré ir a mi cita", INTENT_CANCEL_APPOINTMENT),
    ("Necesito otro horario", INTENT_RESCHEDULE_APPOINTMENT),
    ("Quiero cambiar la hora", INTENT_RESCHEDULE_APPOINTMENT),
    ("¿Puedo mover mi cita para otro día?", INTENT_RESCHEDULE_APPOINTMENT),
    ("Quiero reagendar para mañana", INTENT_RESCHEDULE_APPOINTMENT),
    ("Quiero cancelar mi reservación", INTENT_CANCEL_APPOINTMENT),
    ("Necesito mover mi cita al viernes", INTENT_RESCHEDULE_APPOINTMENT),
    ("¿Puedo cambiar mi horario?", INTENT_RESCHEDULE_APPOINTMENT),
    ("Sí, ese horario está bien", INTENT_CONFIRM_APPOINTMENT),
    ("Ese horario me funciona", INTENT_CONFIRM_APPOINTMENT),
    ("Perfecto, agéndalo", INTENT_CONFIRM_APPOINTMENT),
    ("Sí, quiero ese", INTENT_CONFIRM_APPOINTMENT),
    ("Confirmo ese horario", INTENT_CONFIRM_APPOINTMENT),
    ("Está bien", INTENT_CONFIRM_APPOINTMENT),
    ("Sí, aparta ese", INTENT_CONFIRM_APPOINTMENT),
    ("Me quedo con ese horario", INTENT_CONFIRM_APPOINTMENT),
    ("Agéndalo por favor", INTENT_CONFIRM_APPOINTMENT),
    ("Confirmo la cita", INTENT_CONFIRM_APPOINTMENT),
    ("Agéndame para hoy", INTENT_CREATE_APPOINTMENT),
    ("Quiero cita para el jueves por la tarde", INTENT_CREATE_APPOINTMENT),
    ("Show me availability for Friday", INTENT_CHECK_AVAILABILITY),
    ("Do you have slots this afternoon?", INTENT_CHECK_AVAILABILITY),
    ("Move my appointment to Monday", INTENT_RESCHEDULE_APPOINTMENT),
    ("Can I reschedule my appointment?", INTENT_RESCHEDULE_APPOINTMENT),
    ("Cancel my reservation please", INTENT_CANCEL_APPOINTMENT),
    ("I need to cancel tomorrow appointment", INTENT_CANCEL_APPOINTMENT),
    ("Yes, confirm that slot", INTENT_CONFIRM_APPOINTMENT),
    ("Book that one", INTENT_CONFIRM_APPOINTMENT),
    ("Ok, confirmo", INTENT_CONFIRM_APPOINTMENT),
    ("Quiero confirmar ese horario", INTENT_CONFIRM_APPOINTMENT),
    ("¿Hay disponibilidad para el jueves?", INTENT_CHECK_AVAILABILITY),
    ("¿Puedes agendarme a las 11 am?", INTENT_CREATE_APPOINTMENT),
    ("Necesito reagendar para la próxima semana", INTENT_RESCHEDULE_APPOINTMENT),
]


def test_coverage_for_100_plus_core_appointment_phrases():
    assert len(CASES) == 100
    for phrase, expected_intent in CASES:
        detected = detect_appointment_intent(phrase)
        assert (
            detected["intent"] == expected_intent
        ), f"phrase={phrase!r} expected={expected_intent!r} got={detected['intent']!r}"
